name: Test cases and sonar check

on:
  pull_request:
    branches:
      - master

jobs:
  test-cases:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Step 1 - ğŸ›’ Checkout main branch from Github
        uses: actions/checkout@v2
      - name: Step 3 - âš™ï¸ setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@bhanu-alapati'
      - name: Step 5 - echo statement
        run: echo Complted actions
      - name: Step 6 - npm install
        run: npm install
